--- #YAML:1.0
name:                Gtk2-Ex-WidgetCursor
version:             3
abstract:            Mouse pointer cursor management for Gtk widgets.
license:             gpl
author:              
    - Kevin Ryde <user42@zip.com.au>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Gtk2:                          0
    Scalar::Util:                  0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
